services:
  - type: web
    name: cashback-api
    runtime: python3.11
    rootDir: .
    buildCommand: cd frontend && npm install && npm run build && cd .. && rm -rf static/* && cp -r frontend/dist/* static/ && cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        scope: build
        sync: false
      - key: DATABASE_URL
        scope: runtime
        sync: false
    autoDeploy: true
